# Generated by Django 5.1.4 on 2025-01-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_phone_userprofile_phone_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='middle_name',
            new_name='full_name',
        ),
    ]
