# Generated by Django 5.1.4 on 2025-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_middle_name_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areasofpreparations',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='areasofpreparations',
            name='icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to='areas_of_prepration_icon/'),
        ),
    ]
