# Generated by Django 5.1.4 on 2025-01-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_areasofpreparations_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasofpreparations',
            name='icon_svg',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
