# Generated by Django 5.1.4 on 2025-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_areasofpreparations_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasofpreparations',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
