# Generated by Django 5.1.4 on 2025-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_areasofpreparations_icon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasofpreparations',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
