# Generated by Django 5.1.4 on 2025-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_areasofpreparations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasofpreparations',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
