# Generated by Django 5.1.4 on 2025-02-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_areasofpreparations_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_in_yrs',
        ),
    ]
