# Generated by Django 5.1.4 on 2025-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userprofile_experience_in_yrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasofpreparations',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
