# Generated by Django 5.1.4 on 2025-02-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0006_ebook'),
        ('user', '0010_remove_userprofile_experience_in_yrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded')], max_length=10)),
                ('meeting_url', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
        migrations.CreateModel(
            name='ClassVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(max_length=255)),
                ('video_length_in_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image_url', models.CharField(max_length=500)),
                ('years_of_experience', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teaching_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.areasofpreparations')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInstructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.instructor')),
            ],
        ),
    ]
