# Generated by Django 5.1.4 on 2025-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_image_url',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
