# Generated by Django 5.1.4 on 2025-02-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_instructor_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='package',
        ),
    ]
