# Generated by Django 5.1.4 on 2025-02-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classes_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
