# Generated by Django 5.1.4 on 2025-02-09 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classes_status'),
        ('package', '0009_association_created_at_association_updated_at_and_more'),
        ('user', '0010_remove_userprofile_experience_in_yrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='teaching_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.areasofpreparations'),
        ),
        migrations.CreateModel(
            name='ClassPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
