# Generated by Django 5.1.4 on 2025-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_instructor_teaching_area_classpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classvideos',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
    ]
