# Generated by Django 5.1.4 on 2025-01-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('user', '0005_remove_areasofpreparations_icon_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='areas_of_preparation_id',
        ),
        migrations.AddField(
            model_name='package',
            name='areas_of_preparation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='user.areasofpreparations'),
            preserve_default=False,
        ),
    ]
