# Generated by Django 5.1.4 on 2025-01-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_payment_user_id_remove_userpackage_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
