# Generated by Django 5.1.4 on 2025-02-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_ebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='package',
        ),
        migrations.AddField(
            model_name='ebook',
            name='curriculum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='seo_card_image',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/seo/'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='seo_twitter_card_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='curriculum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.TextField(),
        ),
    ]
