# Generated by Django 5.1.4 on 2025-02-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_remove_ebook_package_ebook_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
