# Generated by Django 5.1.4 on 2025-02-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_association_created_at_association_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.packagesubcategory'),
        ),
    ]
