# Generated by Django 5.1.4 on 2025-02-16 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_alter_subscription_features_alter_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='package.association'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='package.province'),
        ),
    ]
